#!/bin/bash

LIBLITMUS_ROOT=/home/pennpanda/github/liblitmus-precise
SCRIPTS_ROOT=${LIBLITMUS_ROOT}/scripts-oh-measurement/cat-paper
TRACEDATA_ROOT=${SCRIPTS_ROOT}
ST_TRACE_PATH=${TRACEDATA_ROOT}/trace_bin
XEN_TRACE_PATH=${TRACEDATA_ROOT}/trace_bin
TASKSET_ROOT=${SCRIPTS_ROOT}/tasksets_autogenerated
export PATH=${PATH}:${SCRIPTS_ROOT}:.
